### ISSUE TITLE
Shouldn't Justify be a block level tag?

### ISSUE THREAD

**Issue by Alteras1** [Ghan04/discourse-rpn-bbcode#105]
https://github.com/RpNation/discourse-rpn-bbcode/blob/0cc1e929c167061768ab678d892b16856a187674/assets/javascripts/discourse-markdown/bbcode.js.es6#L270

Justify is used to justify content, and should be able to take in other tags

**Comment by Mondrethos** [comment]
Making it a block makes sense to me.
