### ISSUE TITLE
Missing [message] tag for [textmessage]

### ISSUE THREAD

**Issue by Alteras1** [Ghan04/discourse-rpn-bbcode#107]
https://github.com/RpNation/discourse-rpn-bbcode/blob/0cc1e929c167061768ab678d892b16856a187674/assets/javascripts/discourse-markdown/bbcode.js.es6#L382

uhhh... where's the corresponding child tag [message]?

**Comment by Mondrethos** [comment]
I guess it was never finished, Text Message is marked as in progress. Might have been a causality of previously freezing the project.
