### ISSUE TITLE
Block tag is not working????

### ISSUE THREAD

**Issue by Alteras1** [Ghan04/discourse-rpn-bbcode#110]
https://github.com/RpNation/discourse-rpn-bbcode/blob/0cc1e929c167061768ab678d892b16856a187674/assets/javascripts/discourse-markdown/bbcode.js.es6#L514

Uhh, did this ever get fixed? This is using tables. Also the whitelist is missing alot of options.

**Comment by Mondrethos** [comment]
Can it be improved to not use tables?
