### ISSUE TITLE
Clean up CSS for Mail

### ISSUE THREAD

**Issue by Alteras1** [Ghan04/discourse-rpn-bbcode#111]
https://github.com/RpNation/discourse-rpn-bbcode/blob/0cc1e929c167061768ab678d892b16856a187674/assets/javascripts/discourse-markdown/bbcode.js.es6#L635-L643
https://github.com/RpNation/discourse-rpn-bbcode/blob/0cc1e929c167061768ab678d892b16856a187674/assets/stylesheets/bbcode.scss#L273-L291

We can probably take advantage of SCSS and standard CSS to clean up both the HTML and the classes needed for this bbcode

**Comment by Alteras1** [comment]
On second look. this is using three tags when it only really needs one

**Comment by Mondrethos** [comment]
> On second look. this is using three tags when it only really needs one

How can it be moved down to one?

**Comment by Alteras1** [comment]
The original bbcode looked something like this:
```
[mail=send]
[person]Name[/person]
[subject]subject title[/subject]
inline text
[/mail]

[mail=receive]
[person]Name[/person]
[subject]subject title[/subject]
inline text
[/mail]
```

We can reduce it to:
```
[mail type=send person=Name subject="subject title"]
text
[/mail]
```

**Comment by Mondrethos** [comment]
Alright, make it so :D!
