### ISSUE TITLE
Lazy Loading onsite javascript

### ISSUE THREAD

**Issue by Alteras1** [Ghan04/discourse-rpn-bbcode#121]
Reading another discourse markdown plugin, they also used the PluginAPI, but they implemented lazy loading.
https://github.com/unfoldingWord-dev/discourse-mermaid/blob/master/assets/javascripts/initializers/discourse-mermaid.js.es6#L7-L18

We should consider doing lazy loading as well, to reduce the load on the client on any given page.

**Comment by Mondrethos** [comment]
Yes lazy loading is active for all images as of a certain Discourse version. Is that something we can do for BBCodes?

**Comment by Alteras1** [comment]
we can lazy load the js for stuff like accordions and tabs

**Comment by Mondrethos** [comment]
I'm not sure how extreme we can go with lazy loading, could we do the CSS as well, or does that not load until the post is in view?

**Comment by Alteras1** [comment]
We can, but we would have to test for every bbcode tag, which would really just end up adding time to the load
https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/app/lib/load-script.js

**Comment by Mondrethos** [comment]
Fair enough.

**Comment by Mondrethos** [comment]
@Alteras1 Can you setup an example of lazy loading BBCodes? I kinda want to see it.

**Comment by Alteras1** [comment]
https://github.com/RpNation/discourse-rpn-bbcode/tree/feature/lazy-loading

**Comment by Alteras1** [comment]
See the spoiler tag
