### ISSUE TITLE
Anchor tag using Javascript

### ISSUE THREAD

**Issue by Alteras1** [Ghan04/discourse-rpn-bbcode#122]
Was there a reason why we used js for anchor tags? We could just target the `#user-anchor-NAME` in the href.

Also, would this tag work if the target anchor is not loaded on the page? This was originally made for inner post traversal, so it might not be necessary for inter post traveral?

**Comment by Alteras1** [comment]
https://github.com/RpNation/discourse-rpn-bbcode/blob/b64351690385123483eba5f9abd9be9f683ba2ab/assets/javascripts/discourse-markdown/bbcode.js.es6#L1086-L1105

**Comment by Mondrethos** [comment]
I don't remember. I know we had an anchor tag in xF but I believe Discourse might have native anchor functionality?
