### ISSUE TITLE
List tag

### ISSUE THREAD

**Issue by Alteras1** [Ghan04/discourse-rpn-bbcode#124]
Do we try for list tags? We're missing list tags, but the exact tag + structure already exists in the official discourse bbcode plugin:

https://github.com/discourse/discourse-bbcode/blob/f493826eb2edb1fea5c8a96cd9072ff65b5fae09/assets/javascripts/lib/discourse-markdown/bbcode.js.es6#L152-L219

https://github.com/discourse/discourse-bbcode/blob/f493826eb2edb1fea5c8a96cd9072ff65b5fae09/spec/pretty_text_spec.rb#L133-L205

**Comment by Alteras1** [comment]
we would have to alter it quite a bit to perfectly fit how we use list tags, but it'll work

**Comment by Mondrethos** [comment]
We can renake lists into the markdown version I believe?
